"""The dashboard blocks: rule engine, predicted alerts, anomaly, backtest, symptom risk.

The whole design turns on one observation. The naive walk-forward -- loop t, call
`transform_for_inference(history[:t])`, predict -- is 40+ feature builds and 40+ model calls
for a 40-reading history, around 600 ms. It is also unnecessary.

Training pairs features at row t (which read only <= t-1) with `y_sbp_h{h}[t] = sbp[t+h]`.
So `fb.transform` over the FULL submitted history yields, for every t, exactly the feature
row a re-serve at time t would have produced -- and the targets for free. Causality is
structural here, not a promise, so one vectorised build replaces the loop and the backtest
becomes three batched `predict` calls.

Everything below therefore shares one feature frame, built once per request.
"""

import time

import numpy as np
import pandas as pd

from src.logging.logger import logging
from src.utils.ml_utils.feature.cadence import attach_cadence
from src.utils.ml_utils.feature.causal_features import CausalFeatureBuilder
from src.utils.ml_utils.rule_engine.engine import GATE_REASONS
from src.utils.ml_utils.rule_engine.synthetic import ExtendedRuleEngine

SYNTHETIC_WARNING = (
    "Model 4 is trained on labels generated by src/utils/ml_utils/rule_engine/synthetic.py. "
    "No real symptom was ever observed in the HEMOBP corpus. These probabilities describe "
    "the synthetic generator's hazard model, not patient risk, and must not be read as a "
    "clinical prediction.")


def build_panel_frame(predictor, history: pd.DataFrame) -> pd.DataFrame:
    """The causal feature frame over the whole submitted history, built once.

    Uses a FRESH CausalFeatureBuilder rather than `predictor.fb`: `transform()` mutates
    `self.feature_names_`, and `predictor.fb` is shared process state that `predict()` also
    uses. Constructing it from `predictor.config` guarantees identical lags, windows, EWMAs
    and signals, so train/serve parity is preserved.

    The scaffolding below mirrors `causal_features.transform_for_inference`; that function is
    the source of truth and CI asserts the two agree on every shipped feature column.
    """
    g = history.sort_values("ts").copy()
    g["series_id"] = str(g.patient_id.iloc[0])
    g = attach_cadence(g, by="series_id")
    g["step"] = np.arange(len(g))
    g["is_weekend"] = (g.ts.dt.dayofweek >= 5).astype(int)
    for c, default in (("DM", 0), ("is_dm", 0), ("is_male", 0), ("age", 65.0)):
        if c not in g.columns:
            g[c] = default
    return CausalFeatureBuilder(predictor.config).transform(g)


# ------------------------------------------------------------------------ rule engine

def rule_engine_block(registry, panel, threshold, blocked_note="") -> dict:
    """Run the extended engine over the whole submitted history."""
    try:
        if not len(panel):
            return {"error": "no readings to evaluate"}
        pid = str(panel.series_id.iloc[0])
        # Model 2's threshold is keyed in here. `prepare_synthetic_run` also returns a
        # `personal` map, but that one is a coverage heuristic -- clip(q90, 120, 165) -- not
        # Model 2. Using it would compute the learned offset, display it, and then have
        # every personalised rule ignore it.
        personal = {pid: float(threshold)} if threshold is not None else {}
        engine = ExtendedRuleEngine(registry, personal)
        out = engine.run(panel, use_personalisation=bool(personal))
        if not len(out):
            return {"error": "engine produced no rows"}

        last = out.iloc[-1]
        hist = [{"ts": str(pd.Timestamp(r.ts).date()), "fired": bool(r.fired),
                 "tier": r.tier if pd.notna(r.tier) else None,
                 "rule_id": getattr(r, "rule_id", None)}
                for r in out.itertuples()]
        gate = last.get("gate_reason")
        return {
            "current": {
                "fired": bool(last.fired),
                "is_emergency": bool(last.is_emergency),
                "tier": last.tier if pd.notna(last.tier) else None,
                "rule_id": last.get("rule_id"),
                # `.get`, not `getattr`. `last` is a Series and `mode` is a Series METHOD, so
                # attribute lookup finds `Series.mode` before the column of the same name and
                # hands back a bound method. `to_jsonable` then stringifies it instead of
                # raising, so the payload silently carried a method repr -- with the whole row
                # dumped inside it -- where the rule axis was supposed to be.
                "axis_mode": last.get("mode"),
                "gate_reason": gate if gate in GATE_REASONS else None,
            },
            "history": hist,
            "fired_count": int(out.fired.sum()),
            "emergency_count": int(out.is_emergency.sum()),
            "tier_counts": out[out.fired].tier.value_counts().to_dict(),
            # The extended engine deliberately ignores `self.evaluable` and fires rules the
            # registry marks BLOCKED_ON_INPUTS. That is correct at serving: the user supplies
            # the axes the corpus lacks. Saying so keeps this panel from contradicting
            # /api/schema's blocked count.
            "mode": "extended",
            "note": blocked_note,
            "personalised": bool(personal),
        }
    except Exception as exc:                                         # noqa: BLE001
        logging.exception("rule engine block failed")
        return {"error": f"{type(exc).__name__}: {exc}"}


# -------------------------------------------------------------------- predicted alerts

def predicted_alert_block(registry, panel, advisory, threshold) -> dict:
    """Push each forecast horizon's predicted vitals back through the engine."""
    basis = ("Forecast rows are evaluated as confirmed two-measurement sessions dated at "
             "the projected reading. A forecast has no session structure, so the "
             "single-reading gate cannot be evaluated on it.")
    sym_note = ("Today's symptoms are carried forward onto every forecast row. A "
                "symptom-driven tier on a horizon card reflects today's symptoms combined "
                "with a predicted blood pressure -- it is not a predicted symptom.")
    empty = {"horizons": [], "basis": basis, "symptom_note": sym_note}
    try:
        fc = (advisory.get("forecast") or {}).get("sbp") or {}
        if not fc or not len(panel):
            return empty
        dbp_fc = (advisory.get("forecast") or {}).get("dbp") or {}
        pid = str(panel.series_id.iloc[0])
        engine = ExtendedRuleEngine(registry,
                                    {pid: float(threshold)} if threshold is not None else {})
        base = panel.iloc[-1]
        prev_emerg = bool(base.sbp >= 180)
        rows = []
        for key in sorted(fc, key=lambda k: fc[k]["steps_ahead"]):
            node = fc[key]
            r = base.copy()
            r["sbp"] = float(node["point"])
            if key in dbp_fc:
                r["dbp"] = float(dbp_fc[key]["point"])
            r["ts"] = pd.Timestamp(base.ts) + pd.Timedelta(days=node["days_ahead_est"])
            r["step"] = int(base.step) + int(node["steps_ahead"])
            r["reading_age_days"] = 0.0
            # n_meas = 2 is mandatory and disclosed in `basis`. At 1 the gate returns
            # SINGLE_READING_NON_EMERGENCY and every predicted non-emergency is silenced,
            # which would make the whole panel read "nothing due" on a rising forecast.
            r["n_meas"] = 2
            r["prev_emergency"] = prev_emerg
            v = engine.evaluate_row(r, float(threshold) if threshold is not None else None,
                                    prev_emerg)
            prev_emerg = v.get("tier") == "BP_LEVEL_2"
            rows.append({
                "steps_ahead": node["steps_ahead"], "days_ahead": node["days_ahead_est"],
                "sbp": node["point"],
                "dbp": dbp_fc.get(key, {}).get("point"),
                "lo80": node.get("lo80"), "hi80": node.get("hi80"),
                "fired": v.get("tier") is not None,
                "is_emergency": v.get("tier") in ("BP_LEVEL_2",
                                                  "BP_LEVEL_2_SYMPTOM_OVERRIDE",
                                                  "TIER_1_ANGIOEDEMA"),
                "tier": v.get("tier"), "rule_id": v.get("rule_id"),
                "gate_reason": v.get("gate_reason")})
        return {"horizons": rows, "basis": basis, "symptom_note": sym_note}
    except Exception as exc:                                         # noqa: BLE001
        logging.exception("predicted alert block failed")
        return {**empty, "error": f"{type(exc).__name__}: {exc}"}


# ------------------------------------------------------------------------- anomaly

def anomaly_block(predictor, F, history, advisory) -> dict:
    """Per-session detector score in ONE batched call.

    `predictor.detector_score` is the only path that scores Model 3, so the number on this
    chart and the number in the advisory cannot come from different detectors.
    """
    try:
        det = predictor.b.get("detector") or {}
        cut = float(det.get("cut", np.nan))
        raw = np.asarray(predictor.detector_score(F, history.sbp), dtype=float)
        warm_n = int(predictor.config.cold_start_min_readings)
        pts = []
        for i, (ts, s) in enumerate(zip(F.ts, raw)):
            if not np.isfinite(s):
                # The renderer calls toFixed on every point; a null would throw. A score
                # with no inputs is not a zero score, so the point is dropped, not zeroed.
                continue
            warm = i < warm_n
            pts.append({"ts": str(pd.Timestamp(ts).date()), "score": round(float(s), 4),
                        "warmup": warm,
                        "flagged": bool(not warm and np.isfinite(cut) and s >= cut)})
        settled = [p for p in pts if not p["warmup"]]
        ew = advisory.get("early_warning") or {}
        return {
            "points": pts, "cut": round(cut, 4) if np.isfinite(cut) else None,
            "detector": det.get("name"), "budget_pct": det.get("budget_pct"),
            "n_settled": len(settled),
            "n_flagged": sum(1 for p in settled if p["flagged"]),
            "warmup_readings": warm_n,
            "event_definition": ew.get("event_definition"),
        }
    except Exception as exc:                                         # noqa: BLE001
        logging.exception("anomaly block failed")
        return {"points": [], "cut": None, "error": f"{type(exc).__name__}: {exc}"}


# ------------------------------------------------------------------------ backtest

def backtest_block(predictor, F) -> dict:
    """Actual vs predicted over the submitted history, three batched predicts.

    `transform` already computed `y_sbp_h{h}`, so the targets come free and no re-serve loop
    is needed. Horizons are reported as h+1 to match `predict()`'s `steps_ahead`: reporting
    the raw shift here while the forecast table shows h+1 would reintroduce exactly the
    off-by-one the constants block documents fixing.
    """
    try:
        cfg = predictor.config
        cols = predictor.b["feature_names"]
        X = F.reindex(columns=cols)
        warm = int(cfg.cold_start_min_readings)
        med_gap = float(pd.Series(F.ts).diff().dt.days.median() or 2)
        series, horizons = {}, []
        for h in cfg.horizons:
            mdl = (predictor.b["forecasters"] or {}).get(("sbp", h))
            tgt = f"y_sbp_h{h}"
            if mdl is None or tgt not in F.columns:
                continue
            try:
                pred = np.asarray(mdl.predict(X), dtype=float)
            except Exception:                                         # noqa: BLE001
                continue
            act = F[tgt].to_numpy(dtype=float)
            m = np.isfinite(pred) & np.isfinite(act) & (F.step.to_numpy() >= warm)
            if m.sum() < 3:
                continue
            err = pred[m] - act[m]
            key = f"h{h + 1}"
            series[key] = [
                {"ts": str(pd.Timestamp(t).date()), "actual": round(float(a), 1),
                 "predicted": round(float(p), 1), "error": round(float(e), 1)}
                for t, a, p, e in zip(F.ts[m], act[m], pred[m], err)]
            horizons.append({"horizon": h + 1,
                             "days_ahead": round((h + 1) * med_gap, 1),
                             "n": int(m.sum()),
                             "mae": round(float(np.mean(np.abs(err))), 2),
                             "within_10": round(float(np.mean(np.abs(err) <= 10)), 3)})
        return {"horizons": horizons, "series": series,
                "caption": ("These forecasters were fitted on the HEMOBP corpus and applied "
                            "out-of-sample here. The features behind each point read only "
                            "sessions before the one they predict.")}
    except Exception as exc:                                         # noqa: BLE001
        logging.exception("backtest block failed")
        return {"horizons": [], "series": {}, "error": f"{type(exc).__name__}: {exc}"}


# --------------------------------------------------------------------- symptom risk

def symptom_block(predictor, history, as_of=None, full: bool = False) -> dict:
    """Model 4, or an honest statement that this bundle has no symptom heads.

    Scores the NEXT-session horizon only by default. A trained bundle carries a head per
    (symptom x horizon) -- 45 on this cohort -- and each is a CalibratedClassifierCV wrapping
    a gradient booster, scored one row at a time because they are different models and cannot
    be batched. Measured, that was 1,028 ms: more than 60% of the whole request, against the
    10-25 ms this was originally costed at.

    Horizon 0 is the actionable one -- what is likely at the next session -- and the longer
    horizons are a research view, so they sit behind `enrich.symptom_risk_full` rather than
    on the default path. Red flags are never dropped by this filter.
    """
    models = predictor.b.get("symptom_models") if predictor is not None else None
    if not models:
        return {"available": False, "labels_are_synthetic": True, "items": [],
                "warning": SYNTHETIC_WARNING,
                "reason": "this bundle carries no symptom heads; retrain to enable them"}
    try:
        from src.serving.vocabulary import LABELS
        cuts = predictor.b.get("symptom_cuts") or {}
        mech = predictor.b.get("symptom_mechanism") or {}
        reds = set(predictor.b.get("symptom_red_flags") or [])

        horizons = sorted({int(k.rsplit("_h", 1)[1]) for k in models if "_h" in k})
        keep_h = set(horizons) if full else {horizons[0]} if horizons else set()
        selected = {k: m for k, m in models.items()
                    if "_h" not in k or int(k.rsplit("_h", 1)[1]) in keep_h
                    or k.rsplit("_h", 1)[0] in reds}

        row = predictor.fb.transform_for_inference(history, as_of=as_of)
        X = row.reindex(columns=predictor.b["feature_names"])
        items = []
        for key, mdl in selected.items():
            try:
                p = float(mdl.predict_proba(X)[0, 1])
            except Exception:                                         # noqa: BLE001
                continue
            cut = float(cuts.get(key, np.nan))
            base = key.rsplit("_h", 1)[0]
            items.append({"key": key, "label": LABELS.get(base, base),
                          "horizon": int(key.rsplit("_h", 1)[1]) + 1 if "_h" in key else None,
                          "prob": round(p, 4),
                          "cut": round(cut, 4) if np.isfinite(cut) else None,
                          "flagged": bool(np.isfinite(cut) and p >= cut),
                          "mechanism": mech.get(key), "red_flag": base in reds})
        # Red flags first, then by how far past its own cut each one sits. Never averaged
        # into a mechanism score: a red flag next to fatigue is not half a red flag.
        items.sort(key=lambda d: (not d["red_flag"], -(d["prob"] - (d["cut"] or 0))))
        return {"available": True, "labels_are_synthetic": True, "items": items,
                "warning": SYNTHETIC_WARNING,
                "scored": len(selected), "trained": len(models), "full": bool(full),
                "note": ("next-session horizon plus every red flag; set "
                         "enrich.symptom_risk_full for all horizons" if not full
                         else "all horizons"),
                "n_flagged": sum(1 for i in items if i["flagged"])}
    except Exception as exc:                                         # noqa: BLE001
        logging.exception("symptom block failed")
        return {"available": False, "labels_are_synthetic": True, "items": [],
                "warning": SYNTHETIC_WARNING, "reason": f"{type(exc).__name__}: {exc}"}


def history_echo(req) -> list:
    return [{"ts": r.date, "sbp": r.sbp, "dbp": r.dbp, "pulse": r.pulse,
             "weight": r.weight, "n_meas": r.n_meas, "position": r.position,
             "symptoms": list(r.symptoms)} for r in req.readings]


class Timer:
    """Per-block wall clock, reported to the client rather than guessed at."""

    def __init__(self):
        self.t = {}
        self._t0 = time.perf_counter()

    def mark(self, name, start):
        self.t[f"{name}_ms"] = round((time.perf_counter() - start) * 1000, 1)

    def total(self):
        self.t["total_ms"] = round((time.perf_counter() - self._t0) * 1000, 1)
        return self.t
